### PR TITLE
added support for billing edition endpoint

### PR DESCRIPTION
**Pull request by markciecior**
added billing edition endpoint and example script

### CODE REVIEW

**Comment by markciecior** [comment]
Hi @vbscott  - are there any other requirements to get new code like this merged into the PyPI package?

**Comment by vbscott** [comment]
Thank you for the pull request and bringing this to our attention.  We already had internal support for billing and Telephony credits that was never added to this repo.  We just added it to the repo (see #134) along with an example of how to use the new AccountsAdmin class.  Hopefully this works for you, please let us know if there is anything missing.

**Comment by markciecior** [comment]
Thanks @vbscott , this is just what I needed.  Any news on when this would get added to the PyPI package?

**Comment by vbscott** [comment]
We just updated our PyPI package!

**Comment by AaronAtDuo** [comment]
Apparently this had already been done

**Pull request closed without merging**
