### PR TITLE
Update admin.py to include reactivation_url and reactivation_integration_key for Duo Restore

### PR DESCRIPTION
**Pull request by robsmall**
We added support to update the settings for Duo Restore to the AdminAPI. This PR is to add the functionality to duo_client.

### CODE REVIEW

**Comment by mschwager** [comment]
This generally LGTM, but it looks like there's a merge conflict with your other PR. Want to rebase on that commit and amend this?

**Comment by robsmall** [comment]
Whoops, I missed this. Will clean up and fix

**Comment by robsmall** [comment]
Everything should now be all cleaned up :)

**Comment by mschwager** [comment]
Awesome! Thanks @robsmall

**Pull request merged**
